'use client';

export default function Gallery() {
	// TODO: Airtable integration - just got access
	const entryInfo = [
	["Player Pearls", "A vanilla-friendly way to teleport/warp to your friends in survival.", "https://github.com/not-first/player-pearls","https://modrinth.com/mod/player-pearls","https://hc-cdn.hel1.your-objectstorage.com/s/v3/8e27a77b646e682a6a918b7e72bd6be17efce52f_svobvqg.mp4","https://github.com/not-first","https://hackclub.slack.com/archives/U07BBT06UKG","A vanilla-friendly way to teleport/warp to your friends in survival."],
	["ServerSearch", "Search for servers directly from Minecraft", "https://github.com/gabdevele/ServerSearch","https://www.curseforge.com/minecraft/mc-mods/serversearch","https://cloud-acj8ek615-hack-club-bot.vercel.app/0simplescreenrecorder-2025-02-02_18.58.04.mp4","https://github.com/gabdevele","https://hackclub.slack.com/archives/U07E88L3272","A mod that allows you to search for servers directly from Minecraft without having to browse through various websites. This mod only works on Forge but I'm working on extend the compatibility. Mod made for version  1.20.6.\nThis is my first mod and you can check the source code on my github. I didn't upload highseas screenshot because I had problem with it.\nI learnt a lot of things, such as real use of java interfaces and multithreading (for web requests).\n "],
	["Command Reporter", "Command Reporter is a Minecraft Spigot plugin that reports player commands to a Discord channel through webhook.", "https://github.com/asmahdi08/CommandReporterMinecraft","https://modrinth.com/plugin/command-reporter","https://cloud-azrjpeie1-hack-club-bot.vercel.app/0command_reporter_demo.mp4","https://github.com/asmahdi08","https://hackclub.slack.com/archives/U04G7T2163T","The Command Reporter Plugin is a Minecraft plugin that reports player commands to a Discord webhook. It is designed to help server administrators monitor and manage player activities by sending notifications to a specified Discord channel.\nI actually submitted it a while ago, it needed some improvements, so I worked on it a bit more and am resubmitting it. The version 1.0.1 was the previous one. The version 1.1.0 is the latest one."],
	["Camera Tweaks", "A fancy mod with freecam, zoom, fullbright, freelook, no fog and custom third persons!", "https://github.com/ItsFelix5/CameraTweaks","https://modrinth.com/mod/cameratweaks","https://hc-cdn.hel1.your-objectstorage.com/s/v3/1d7bee50cc476398b7185e6a42a9e46347ace9ff_2025_01_09_18_33_27___trim__tx1af3mmv8k_.mp4","https://github.com/ItsFelix5","https://hackclub.slack.com/archives/U07AGEVSTD2","A great client side mod (not biased) that allows you to use freecam, detatch your camera, save camera positions, fullbright, (a very fancy) zoom and disable some pesky fog (this is very useful in the nether and underwater)"],
	["Italian Food", "Italian Food Minecraft Mod brings a taste of Italy to your Minecraft world by introducing a variety of authentic Italian dishes. Craft and enjoy foods like focaccia, pizza, mozzarella, taralli, espresso, and tiramisù, each offering unique in-game effects", "https://github.com/Rayanlupo/Italian-Food-Minecraft-Mod","https://modrinth.com/mod/italian-food","https://hc-cdn.hel1.your-objectstorage.com/s/v3/ab3cb7d1af4c16306f08342110b3f32ceaa3f16b_italian_food_in_minecraft_-_mod_demo__mbhqjwg1724_.mp4","https://github.com/Rayanlupo","https://hackclub.slack.com/archives/U074C9BE604","I made  a mod that adds Italian food to Minecraft, each food gives the player a unique effect, like espresso gives you speed due to its caffeine and pizza gives you regeneration"],
	["Goose's Useless Stuff", "Adds some useless stuff like trash.", "https://github.com/CharmedGoose/Useless-Stuff","https://modrinth.com/mod/gooses-useless-stuff","https://cloud-qo9g004wo-hack-club-bot.vercel.app/0demo.mp4","https://github.com/CharmedGoose","https://hackclub.slack.com/archives/U08160NAQ79","A mod that adds useless stuff like trash."],
	["Paper Asylum", "Adds several items from Item Asylum (Roblox) to Minecraft.", "https://github.com/MelnCat/PaperAsylum","https://modrinth.com/plugin/paper-asylum","https://encrypting.host/wHHQuc455Y.mp4?key=Ih4yblWegI5Mnn","https://github.com/MelnCat","https://hackclub.slack.com/archives/U074R9DGELB","A Minecraft plugin that Implements several items from Item Asylum and also implements its mechanics into the game.\nAdds many items from Item Asylum (a Roblox game) such as Moscow, America, London, Train, Ultra Instinct, Warp, Bible, Chicago, Distressed red ball, Death note, Wand, Aple [sic], and Air. Everything is added through a plugin, so no mods are needed for clients to join the server, while custom features are still added such as custom textured armor (ultra instinct), custom items, and custom sound effects.\nWhen you join the game, you will get 3 random items (one melee, one ranged, and one misc) to be used to assist in killing players. Every time you die, you reshuffle and gain a different set of 3."],
	["Magic Wands", "A mod that adds magic wands and spells that allow unique and destructive combinations!", "https://github.com/Dimitris-Toulis/magic-mod","https://modrinth.com/mod/magic-wands","https://cloud-2ab3tihty-hack-club-bot.vercel.app/0mw.mp4","https://github.com/Dimitris-Toulis","https://hackclub.slack.com/archives/U07D53W8L6R","This fabric mod adds magic wands and spells along with blocks that interact with them. There are many unique spell combinations to create powerful and useful wands. There 3 tiers of wands and spells allowing progression since each one is harder to get than the previous one."],
	["Better Pearls", "Ride ender pearls with this mod!", "https://github.com/NotIshi28/BetterPearlsMod","https://legacy.curseforge.com/minecraft/mc-mods/better-pearls","https://cloud-r7gojfswi-hack-club-bot.vercel.app/0betterpearls.mp4","https://github.com/NotIshi28","NU079QQC1BEZ","Better Pearls is a fun and innovative Minecraft mod that takes ender pearl mechanics to the next level! With this mod, you can ride ender pearls as they travel, and they now bounce off walls, the ground, and even water."],
	["EaterMod", "Mod where you can eat mob souls to gain certain cool and op effects", "https://github.com/RR-CREATOR/eater-mod-1.21","https://modrinth.com/mod/eatermod","https://cloud-icaiwibfa-hack-club-bot.vercel.app/0minecraft__1.mp4","https://github.com/RR-CREATOR","https://hackclub.slack.com/archives/U081RRUA09W","Mod where you can eat mob souls to gain certain cool and op effects"],
	["Kitty Mod", "A mod that adds a bunch of cat themed items such as collars, treats, and a cat bed!", "https://github.com/AlanikREDAWN/kitty-mod-v2-template-1.21","https://modrinth.com/mod/kitty-mod","https://cloud-ohkduff70-hack-club-bot.vercel.app/0screen_20recording_202025-01-29_20at_2012.mp4","https://github.com/AlanikREDAWN","https://hackclub.slack.com/archives/U07AZFQLPQ8","This project is an Minecraft mod that adds all the essentials for your little kitty friend!\n"],
	["World Border Expansion", "A fun plugin that expands your world border when something dies!", "https://github.com/22yeets22/World-Border-Expansion","https://modrinth.com/plugin/world-border-expansion","https://cloud-eir6r86s7-hack-club-bot.vercel.app/0world_border_expansion_video.mp4","https://github.com/22yeets22","https://hackclub.slack.com/archives/U0807K23FPG","A fast and lightweight plugin that expands the world border when a mob dies!\nStart off in a small world, and slowly expand your world to gather materials!"],
	["Plunder", "A server-sided Fabric Minecraft mod that implements a unique loot-dropping system.", "https://github.com/William-Chapin/Plunder-Mod","https://modrinth.com/mod/plunder","https://cloud-dal0x266g-hack-club-bot.vercel.app/00118_1_.gif","https://github.com/William-Chapin","https://hackclub.slack.com/archives/U082AEBD4AC","A server-sided Fabric Minecraft mod that implements a unique loot-dropping system.\nWhenever a player takes damage, whether from PVP or from natural causes (configurable), they have a chance to drop some of the items from their inventory onto the ground. Steal others items in already chaotic PVP!"],
	["Rainbow Gear", "A server sided Minecraft Mod to add 6 new custom armor and tool sets, each one being a color of the rainbow.", "https://github.com/Win10MC/Rainbow-Gear","https://modrinth.com/mod/rainbowgear","https://cloud-okusvwbbc-hack-club-bot.vercel.app/0demo3333-ezgif.com-optimize.gif","https://github.com/Win10MC","https://hackclub.slack.com/archives/U08177GA39V","A Minecraft Mod to add 6 new custom armor and tool sets, each one being a color of the rainbow."],
	["Nibbles' Deep Dark", "A mod that adds weapons that inherit the attacks of the warden!", "https://github.com/Nibbl-z/NibblesDeepDark","https://modrinth.com/mod/nibbles-deep-dark","https://www.youtube.com/watch?v=ZecwYSu0938","https://github.com/Nibbl-z","https://hackclub.slack.com/archives/U079E6V7R28","The Warden will now drop its heart, which will allow you to upgrade your netherite and ranged weapons with its powers, creating Echo Weapons.\nFeatures\nWarden Heart: Dropped from the Warden upon death. When combined with a weapon and an echo shard in a smithing table, it upgrades the weapon to Echo tier.\nEcho Sword/Axe: An upgrade from the netherite counterpart, dealing more damage and having the chance to inflict knockback and the darkness effect on those attacked.\nEcho Bow/Crossbow: When shot, this weapon will perform the Warden's sonic boom attack, piercing through several mobs and dealing significant damage.\nSculk Dust and Arrows: Gather sculk dust by mining sculk blocks, and upgrade regular arrows with 4 sculk dust in order to make them usable with the Echo Bow and Echo Crossbow."],
	["Simple Edits", "Adds 5 items that help with building to minecraft", "https://github.com/1rom11/SimpleEdits/","https://modrinth.com/mod/simpleedits","https://www.youtube.com/watch?v=l2cXye38H4c","https://github.com/1rom11","https://hackclub.slack.com/archives/U07PUQ9269X","Simple Edits is a Minecraft mod that adds tools for editing blocks in the game. It provides a selection wand for replacing blocks, a block state changer for modifying certain block states, and a water drain wand for removing water from an area."],
	["Obamium Mod", "A small mod that adds incredibly new and OP materials Obamium and More to the game", "https://github.com/duck123acb/ObamiumMod","https://modrinth.com/mod/obamium-mod","https://www.youtube.com/watch?v=gnL7EsDX4pU","https://github.com/duck123acb","https://hackclub.slack.com/archives/U04DDHF5DFB","A small mod that adds incredibly new and OP materials Obamium and Bidenite to the game\nfor some reason i couldnt update my old high seas ship on the same project so i made two different ones that add up to 9 hours."],
	["Portal Gun Mod", "Adds portals, portal gun and a few recipes", "https://github.com/Jan3385/PortalGunMod","https://modrinth.com/mod/portal-gun-mod","https://youtu.be/BP8RQ7fzakE","https://github.com/Jan3385","https://hackclub.slack.com/archives/U07DG5AQ0RK","Portal Gun mod for Minecraft 1.20.1 Forge. It allows easy transportation and exploration\n"],
	["2D Minecraft", "Minecraft but only with a 3 block wide strip, a recreation of the 2D craft mod", "https://github.com/cheyao/minecraft-plugin","https://modrinth.com/mod/2d-minecraft","https://youtu.be/DVMfVSMXZ98","https://github.co/cheyao","https://hackclub.slack.com/archives/U07EQJY9YDD","Ever wanted to play 2D minecraft? Here is the mod for you!\nFeaturing a locked in place 2D camera and a 2D world generator, unleash your imagination in this terraria like world!"],
	["Votes Update", "Bring back 23w13a_or_b to newer version!", "https://github.com/MathiasDPX/VoteUpdate","https://modrinth.com/plugin/voteupdate","https://youtu.be/uCjqyg2I4UE","https://github.com/MathiasDPX","https://hackclub.slack.com/archives/U080HHYN0JD","Bring back 23w13a_or_b to newer version!\nThis plugin bring back functionnalities of the april fools version 23w13a_or_b to newer Minecraft version,\nWith 21 votes availables"],
	["Shulkr", "A companion plugin for Shulkr/Mclo.gs that enables seamless log management and uploading directly from your Minecraft server.", "https://github.com/Paylicier/ShulkrCompanion","https://modrinth.com/plugin/shulkr","https://youtu.be/p1nLo6MJl1Y","https://github.com/Paylicier","https://hackclub.slack.com/archives/U080DB49RCY","A companion plugin for Shulkr (another project i made for highseas) that enables seamless log management and uploading directly from your Minecraft server.\n"],
	["Schrodingers Chest", "A Minecraft mod that adds not Schrödinger's Cat, but Schrödinger's Chest!", "https://github.com/Qwatrum/SchrodingersChest","https://modrinth.com/mod/schrodingers-chest","https://youtu.be/w-caBmNzTTA","https://github.com/Qwatrum","https://hackclub.slack.com/archives/U07DK1S7KTP","SchrodingersChest is a Fabric Minecraft mod adding a staff which can be used to right click a structure chest to change its loot. And to obtain relic items with which you can craft special tools.\n"],
	["Simon-Says", "A fun minigame to play with friends.", "https://github.com/iambodha/Simon-Says","https://modrinth.com/plugin/simon-says","https://www.youtube.com/watch?v=Wj4O3jnKhG4","https://github.com/iambodha","https://hackclub.slack.com/archives/U07N7HEJKMF","Simon Says is a fast-paced minigame that brings the classic game of Simon Says to Minecraft. Players face various tasks and challenges, but they must carefully follow Simon's instructions—only performing actions when Simon says so. As the game progresses, a zone begins closing in, forcing those who’ve followed Simon’s orders to fight it out in the shrinking space."],
	["PixelRealms", "A forge 1.21.1 mod called PixelRealms... I stopped with this mod hallway since I will start working on 1.20.1 with more tech renovations and better features.", "https://github.com/scattercat-123/pixelrealms_forgemod_1.21.1/","https://modrinth.com/mod/pixelrealms","https://youtu.be/uimiLjRJLmw","https://github.com/scattercat-123","https://hackclub.slack.com/archives/U08372M7D25","Yo! Welcome to PixelRealms – a tech mod that's all about Light Orbs and good vibes. If you're into Optifine and JEI, you’re gonna love this one. It’s got a bit of everything, from fancy blocks to power-up items, and it all runs smoother than your last Minecraft server."],
	["TecnoGUI", "A QOL mod for Tecnocraft Roleplay.", "https://github.com/ReLoia/TecnoGUI","https://modrinth.com/mod/tecnogui","https://www.youtube.com/watch?v=4ENakbhQgDE","https://github.com/ReLoia","https://hackclub.slack.com/archives/U078B469URL","A feature rich QOL mod for Tecnocraft Roleplay. It changes the UI and adds functionality to enhance the quality of the gameplay.\n"],
	["Snowball Hole Filler", "Mod that uses snowballs to automatically fill nearby holes with natural-looking blocks. It supports customizable radius and depth, tracks statistics, and includes an undo feature for added flexibility.", "https://github.com/PawiX25/Snowball-Hole-Filler","https://modrinth.com/mod/snowball-hole-filler","https://youtu.be/Ftgc5-r5oJY","https://github.com/PawiX25","https://hackclub.slack.com/archives/U07G64ESXKR","Mod that uses snowballs to automatically fill nearby holes with natural-looking blocks. It supports customizable radius and depth, tracks statistics, and includes an undo feature for added flexibility."],
	["Not Apples", "This mod lets you craft unique apples, each with special powers.", "https://github.com/MMc-Minecraft/Apples-Mod","https://modrinth.com/mod/not-apples","https://youtu.be/OaiMwb_iSNo","https://github.com/MMc-Minecraft/","https://hackclub.slack.com/archives/U07H0E962KH","Not Apples Mod is a Minecraft mod that lets you craft a variety of unique apples, each offering special effects to enhance your gameplay. These apples can aid you in battles, exploration, and more."],
	["Simple Spotify Controller", "A super simple mod for Fabric that allows you to control your Spotify App from inside Minecraft!", "https://github.com/CattoYT/SimpleSpotifyController","https://modrinth.com/mod/simplespotifycontroller","https://www.youtube.com/watch?v=bfFrC5vcbMc","https://github.com/CattoYT","https://hackclub.slack.com/archives/U0786TENDM5","Have you ever been playing Minecraft with Spotify but you had to keep tabbing over? Don't you wish that you could just run some ingame commands to switch playlist, or play a song?\nThis mod intends on giving you a simple, lightweight way of controlling Spotify without having to leave Minecraft's chat."],
	["Karnx's miscs!", "A Sword Mod with Endless Possibilities","https://github.com/Fastestkyo", "https://www.curseforge.com/minecraft/mc-mods/karnxs-miscs","https://hc-cdn.hel1.your-objectstorage.com/s/v3/1f41a61f26917ae089f9329f85c1e7f68a403a09_2025-01-26_10-14-40.mp4","https://github.com/Fastestkyo/Karnx-s-Miscs-minecraft--fabric--1.21-","https://hackclub.slack.com/archives/U082Z7WDHSQ","# **Karnx's Miscs!**\n### A Sword Mod with Endless Possibilities\nKarnx's Miscs is a Minecraft mod that introduces over 15 unique and exciting swords, each with its own abilities and features. Perfect for players who love to spice up combat and exploration!\n## 1. **Swords Included-**\n> - Confident Sword\n> - Dagger\n> - Eclipse Sword\n> - Ender Sword\n> - Frozen Sword\n> - Gravity Sword\n> - Hammer Item\n> - Katana Sword\n> - Lucky Sword\n> - Machine Gun\n> - Magnet Sword\n> - Necro Sword\n> - Phantom Sword\n> - Phoenix Sword\n> - Quick Sword\n> - Shadow Sword\n> - Soul Sword\n> - TNT Sword\n> - Tomahawk Item\n> - Volcanic Sword\n## 1. **Tools**\n> - Chisel Item\nEach weapon and tool brings a unique playstyle and utility to your game, offering endless fun and creativity!\nDownload now and explore the world of Karnx's Miscs!"],
	["Magic Craft", "A magic mod that adds magic staffs that have different elements like Fire, Earth, Wind, Lunar, Solar, Lava, Lightning, Ice, Eclipse, Quantum.", "https://github.com/DylM0nster22/HackCraft","https://modrinth.com/mod/magic-craft","https://cloud-leomjynqr-hack-club-bot.vercel.app/0screen_recording_2024-11-26_154127.mp4","https://github.com/DylM0nster22","https://hackclub.slack.com/archives/U072819C9B5","What is this mod\nThis mod is a magic mod that i am devolping with some cool magic staffs\nStaff Abilities:\nFire Staff: Shoot fireballs to burn enemies and light up your surroundings.\nIce Staff: Freeze entities in place with blocks of ice for a short time.\nLightning Staff: Call down a lightning bolt at a targeted location.\nEarth Staff: Knock back enemies and deal damage with a ground slam.\nWind Staff: Create a tornado that lifts entities into the air.\nLava Staff: Control lava to reshape the battlefield or create hazards.\nQuantum Staff: Teleport up to 100 blocks to a safe and open space.\nSolar Staff: Shoots a wall of fire that deals knockback and lights entities on fire.\nLunar Staff: Shoots a concentrated beam of moonlight that has a long range.\nEclipse Staff: Creates a black hole that sucks entities in and then implodes.\nWater Staff: Shoots a beam of water at any enemy in your sight\nObsidian Staff: Encases you in obsidian to protect you for 5 seconds\nHow It Works:\nEach staff is crafted using elemental crystals and follows standard crafting recipes.\nparticles make the staffs feel cool, and cooldowns make every staff feel balanced."],
	["Wakatime mod", "A mod which records your playtime into wakatime", "https://github.com/NeonGamerBot-QK/wakatime-mod/","https://modrinth.com/mod/wakatime-mod","https://github.com/NeonGamerBot-QK/wakatime-mod/blob/master/assets/demo.mp4?raw=true","https://github.com/NeonGamerBot-QK","https://hackclub.slack.com/archives/U07L45W79E1","This fabric mod is for counting your hours in minecraft as you play the game.\nYou can currently config the api key in the config file to connect to wakatime.\nwakatime will report this as gaming/browsing time and report it on the correct interval of when you break blocks."],
	["NameManager", "Lets you set a client-side name to entities and players", "https://github.com/Brelee2222/NameManager","https://modrinth.com/mod/namemanager","https://youtu.be/L41HGZwdn_w","https://github.com/Brelee2222","https://hackclub.slack.com/archives/U06HSAREL3U","What if you're having trouble keeping track of your pets? What about your villagers with different trades? This mod allows you to nickname players and entities!\n"],
	["Feast", "Finally, a good food mod.", "https://github.com/spjoes/Feast/","https://modrinth.com/mod/feast1","https://youtu.be/iCwXrJ4ubnU","https://github.coU07A7DQNCAV","I think current food mods are too \"\"vanilla unfriendly\"\". They take away from the game too much and I dislike that. I decided to start a mod that can slot directly beside vanilla--enhancing vanilla's features."],
	["Nugget", "adds the famous nugget to mincraft!", "https://github.com/sillyangel/nugget/","https://modrinth.com/mod/nuggetmod","https://cloud-7mtwh5uek-hack-club-bot.vercel.app/12025-01-05_21-20-13.mp4","https://github.com/sillyangel","https://hackclub.slack.com/archives/U083H6XP1H6","'- **Nugget** is a Minecraft 1.21 Forge Mod that brings the iconic Chicken Nugget Meme (Gegagedigedagedago) into the world of Minecraft!\n		- This mod includes:\n			- **Nugget Tools**\n			- **Nugget Armor** (for both players and horses)\n			- **Armor Trim**\n			- **Nugget Trim Material**\n			- A custom **music disc** and **painting**\n			- Nugget **ores** (stone and deepslate variants)\n			- **Raw Nugget and Raw Nugget Block**\n			- **Nugget and Nugget Blocks**"],
	["MC Game of Life Sim", "This is a port of Conway's Game of life into Minecraft! You can spawn a grid and interact to change the cell states, and then simulate to see what happens!", "https://github.com/cyberneel/gmae-of-life-player","https://modrinth.com/mod/mc-game-of-life-sim","https://cloud-psgyg7fdg-hack-club-bot.vercel.app/0cleanshot_2025-01-07_at_18.08.29-converted.mp4","https://github.com/cyberneel","https://hackclub.slack.com/archives/U079JRQL6F9","# What is it?\nThis mod is basically a port of the famous Conway's Game of Life. The game is simple, you edit state of the grid and simulate the next step to see how it evolves based on pre-set rules.\n## The Rules\n1. Any live cell with fewer than two live neighbours dies, as if by underpopulation.\n2. Any live cell with two or three live neighbours lives on to the next generation.\n3. Any live cell with more than three live neighbours dies, as if by overpopulation.\n4. Any dead cell with exactly three live neighbours becomes a live cell, as if by reproduction.\n# How to use?\nYou can create a 10x10 grid by running the command:\n```\n/spawn_gol_grid\n```\nThis will create a gray grid nearby for you to interact with. Breaking a block removes the entire grid, while \"\"using\"\" or right-clicking on a block toggles its state between Alive (Red) and Dead (Gray).\nOnce you are ready and want to see how your grid evolves, run the following command:\n```\n/simulate_gol_step [steps count]\n```\nThis will simulate the grid by the specified steps, you can keep running this command to see more evolution steps, or modify the grid before another simulation step. You can also right-click the magenta block to quickly simulate a step.\n# What's Next?\nI plan on adding more features and making the experience better as I learn more about MC modding. Some things I have planned are:\n- Better colors and textures\n- Reverse simulation\n- A control block for settings\n"],
	["Aviros", "A new dimension with a new ore, new tools, and new armor! (better than netherite)", "https://github.com/durocodes/aviros","https://modrinth.com/mod/aviros","https://www.youtube.com/watch?v=HomWi05s9N4","https://github.com/durocodes","https://hackclub.slack.com/archives/U081VJKBNBS","A new dimension, Aviros. Inside of the Aviros dimension, you can find Jynwood and Skyrite—which are used to make Skyrite tools and armor, which is slightly better than netherite."],
	["Death Note Mod", "A minecraft mod that adds death note items from the Anime!", "https://github.com/ericafk0001/Death-Note-1.21.X","https://modrinth.com/mod/mc-death-note-mod","https://www.youtube.com/watch?v=mRzcB2U3BUk","https://github.com/ericafk0001","https://hackclub.slack.com/archives/U07UE65BQHG","A Fabric Minecraft mod for Version 1.21 that adds a few new items to the game from the death note anime. The death note is basically a writable book item that when entered any entities name or player it will kill them. For entities, the nearest one will be killed upon written their name."],
	["Gateways", "A vanilla-esque teleport pad mod for both blocks and entities with redstone compatibility", "https://github.com/axalatar/gateways","https://modrinth.com/mod/gateway","https://youtu.be/-Oy_6R89u_k","https://github.com/axalatar","https://hackclub.slack.com/archives/U082SM5PRA4","A mod that adds automatable vanilla-esque teleport pads with cool visual effects. (If you want the full docs, it's on both the modrinth and github)"],
	["Potato Perks!", "Potatoes that give you super powers!", "https://github.com/Bluelightning26/potato-perks-1.21.1","https://modrinth.com/mod/potato-perks","https://hackclub.slack.com/archives/C016DEDUL87/p1738118290247989","https://github.com/Bluelightning26","https://hackclub.slack.com/archives/U0824G9PTFE","Potatoes With Superpowers!\nCraft Powered Potatoes with cool special effects! In the form of blocks they can make you faster, jump, higher, or even slip around! Cook, then consume the potatoes to see the effect of these perks on the fly! Use the special Potato Portal to switch between the different awesome potato abilities by throwing a potato on it! There is plenty of fun to be had and many unique mini-game opportunities!"],
	["FKG", "A mod that aids in pricing for kuudra items.", "https://github.com/JeffreyWangDev/fkg-mod","https://modrinth.com/mod/fkg","https://www.youtube.com/watch?v=G3LUIZfmlbc","https://github.com/JeffreyWangDev","https://hackclub.slack.com/archives/U04J5APLPJ9","FKG Mod is a Minecraft mod designed specifically for Hypixel Skyblock. It helps players get prices for Kuudra items efficiently. This is a free version of the kuudra gang mod! It offers a FREE attribute upgrade command\n"],
	["Item randomizer", "Minecraft plugin that randomize the item player get!", "https://github.com/duykhanh09103/Item_randomizer","https://www.spigotmc.org/resources/item-randomizer.121153/","https://youtu.be/mq932v-L3Ac","https://github.com/duykhanh09103","https://hackclub.slack.com/archives/U081GA0TAPR","Minecraft plugin that randomize the item player get!\nyou can play normal and just give the player item by using /itemrand start or you can use /RandWorldGame start for a minigame!"],
	["Villager Tower Mod", "This mod includes custom items, blocks and crafting recipe. And most importantly adds a custom structure called villager tower that is similar to the pillager tower but with village theme loot.", "https://github.com/TextualMite9145/big-mod-1.21.1","https://modrinth.com/mod/villager-tower-mod","https://cloud-5aide0jm0-hack-club-bot.vercel.app/0desktop_2025.01.21_-_09.52.52.08.mp4","https://github.com/TextualMite9145","https://hackclub.slack.com/archives/U08912PQYTA","This mod adds:\nvillager tower - similar to a pillager outpost but has village theme loot and is designed to look like a villager could live and work there\nPink garnet group - decorative item and block\nPink apple - custom food only obtainable in creative\nCustom Ore Generation - generates pink garnet ore and deepslate ore"],
	]

  return (
    <div>
    {entryInfo.map((info, index) => {
      let videoSrc = info[4];
      if (videoSrc.includes('youtube.com/watch') || videoSrc.includes('youtu.be')) {
        const url = new URL(videoSrc);
        const videoId = url.searchParams.get('v') || url.pathname.split('/').pop();
        videoSrc = `https://www.youtube.com/embed/${videoId}`;
      }
      
      return (
        <div key={index}>
          <p style={{ whiteSpace: 'pre-line', position: 'relative', cursor: 'pointer', textDecoration: 'underline dotted', textDecorationThickness: '3px' }} onMouseEnter={(e) => {
              const tooltip = document.createElement('div');
              tooltip.innerText = info[1];
              tooltip.style.position = 'absolute';
              tooltip.style.background = 'rgba(0, 0, 0, 0.7)';
              tooltip.style.color = 'white';
              tooltip.style.padding = '10px';
              tooltip.style.borderRadius = '5px';
              tooltip.style.top = '100%';
              tooltip.style.left = '0';
              tooltip.style.right = '0';
              tooltip.style.marginLeft = 'auto';
              tooltip.style.marginRight = 'auto';
              tooltip.style.textAlign = 'center';
              tooltip.style.zIndex = '1000';
              tooltip.style.fontSize = '0.8em';
              tooltip.style.opacity = '0';
              tooltip.style.transition = 'opacity 0.3s ease-in-out';
              tooltip.id = `tooltip-${index}`;
              const target = e.target as HTMLElement;
	      target.appendChild(tooltip);
              setTimeout(() => { tooltip.style.opacity = '1'; }, 10);
            }}
            onMouseLeave={() => {
              const tooltip = document.getElementById(`tooltip-${index}`);
              if (tooltip) {
                tooltip.style.opacity = '0';
                setTimeout(() => {
                  if (tooltip.parentNode) {
                    tooltip.parentNode.removeChild(tooltip);
                  }
                }, 300);
              }
            }}>{info[0]}</p>
          {videoSrc.includes('youtube') ? (
            <iframe
              width="560"
              height="315"
              src={videoSrc}
              title="YouTube video player"
              frameBorder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowFullScreen
            ></iframe>
          ) : info[4].endsWith('.gif') ? (
            <img src={info[4]} alt="GIF" style={{ width: '40%' }} />
          ) : (
            <video controls src={info[4]} style={{ width: '40%' }} />
          )}
          <br />
          <a href={info[2]} target="_blank" rel="noopener noreferrer">GitHub</a>{' '}
          <a href={info[3]} target="_blank" rel="noopener noreferrer">Modrinth</a>{' '}
          <a href={info[5]} target="_blank" rel="noopener noreferrer">Creator's GitHub</a>{' '}
          <a href={info[6]} target="_blank" rel="noopener noreferrer">Chat with Creator</a>
          <hr />
        </div>
      );
    })}
    </div>
  );
}
